### PR TITLE
Adding Xcode project for being installable by Carthage

### PR DESCRIPTION
**Pull request by gergelysanta**

### CODE REVIEW

**Comment by gergelysanta** [comment]
For being installable by Carthage, a new tag will be needed to create after/if this PR is merged.
Carthage works with tags. It will fetch the latest tagged version, which is actually `1.2.0` and that's not buildable by Carthage.

**Comment by Bouke** [comment]
Thank you for taking the time to contribute. However I don't feel like supporting any build system other than SwiftPM at the moment. Adding support for other build system also introduces an expectancy of me as maintainer to ensure that those keep working and thus adds an additional maintenance burden.

**Comment by gergelysanta** [comment]
This is very unfortunate 😞 Supporting more build systems helps to keep projects simple. This way you force others to use SwiftPM in their projects even if they have Carthage dependencies already set up. I'm OK to maintain Carthage fork for myself but later I'll have to move my repository to a private space.

**Comment by Bouke** [comment]
I understand your position and it's a valid concern. However I don't force others to use this library, so free to fork and customise it the way you like.

**Pull request closed without merging**
