### PR TITLE
Make all ResourceRecord fields modifable

### PR DESCRIPTION
**Pull request by mcfedr**
Everything else is modifable, and its would be convient for these to be as well, especially as the implementations are already modifable

### CODE REVIEW

**Comment by Bouke** [comment]
In what situations do you need to work with an editable `ResourceRecord`? In most of my use cases I’m working wih the explicit types conforming to this protocol, so there’s no need to mark those fields editable through the protocol.

**Comment by Bouke** [comment]
It might be possible for users of the package to create their own structs or classes that conform to that protocol, so requiring editability might not even be possible for their types. I don’t know if this sort of extensibility is something worthwhile.

**Comment by mcfedr** [comment]
It seemed to make sense because all the rest of the `Message` is editable, and if I use a specific RR type, it would be editable, only when referring to the protocol it becomes read only.

I sort of see what you mean about extensibility, but there would be plenty of other questions to ask, like how it fits into (un)serializer and the enforced standard fields.

I need this because I writing a dns proxy that is replacing the names in RRs in some cases, I actually am not working with specific types, I just change all of them, this makes sense for what I need to achieve. I could replace the RRs with new ones, but it feels weird when I can edit everything else in place.

**Comment by Bouke** [comment]
I'm fine with merging this. If there is a more worked out idea on how to embrace extensibility, we could revisit this.

**Pull request merged**
