### PR TITLE
Fix Swift5 warnings

### PR DESCRIPTION
**Pull request by gergelysanta**
I'm not mastering UnsafePointers, so the last commit may be not ideal...

### CODE REVIEW

**Comment by Bouke** [comment]
Thanks! Can you replace the tabs with 4 spaces, to match this project’s code style?

I’m also not a big fan of the unsafe pointers api design and dreading touching anything once it appears to work.

I’ll try make some time for an in depth review later on.

**Comment by Bouke** [comment]
Also, I’d be interested to hear your use-case for this library?

**Comment by gergelysanta** [comment]
I replaced tabs with spaces.

I use this library in a macOS NetworkExtension for watching DNS traffic. It's super easy, just calling `Message(deserialize:)` on incoming/outgoing data and there it is. Thanks for the good work! 👍🏼

**Comment by Bouke** [comment]
> Didn't you think of renaming the class by the way? It's not really descriptive in the content filter environment as it's not saying anything about what type of message it is. What about `DNSMessage`?

The plan for Swift was originally to have great namespacing support, similar to Python. So the idea would be that the library name would have a more prominent meaning to the class' name. As namespaces aren't really a thing, so we might consider renaming the class to make more sense.

**Comment by Bouke** [comment]
Merged in 82ea7227a4cfc12f2986513a2470de9980f809f6, thank you!

**Pull request closed without merging**
